//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:   64 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  128 Size:    64
//   float3 gEyePosW;                   // Offset:  192 Size:    12 [unused]
//   float gNearZ;                      // Offset:  204 Size:     4 [unused]
//   float gFarZ;                       // Offset:  208 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  212 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  216 Size:     8 [unused]
//   float gDeltaTime;                  // Offset:  224 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbPerObject                       cbuffer      NA          NA            cb0      1 
// cbPass                            cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[4], immediateIndexed
dcl_constantbuffer CB1[12], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- vIn.PosL.x; v0.y <- vIn.PosL.y; v0.z <- vIn.PosL.z; 
//   v1.x <- vIn.Col.x; v1.y <- vIn.Col.y; v1.z <- vIn.Col.z; v1.w <- vIn.Col.w; 
//   o1.x <- <VS return value>.Col.x; o1.y <- <VS return value>.Col.y; o1.z <- <VS return value>.Col.z; o1.w <- <VS return value>.Col.w; 
//   o0.x <- <VS return value>.PosH.x; o0.y <- <VS return value>.PosH.y; o0.z <- <VS return value>.PosH.z; o0.w <- <VS return value>.PosH.w
//
#line 34 "C:\dev\DirectX\DirectXBasicRendering\DirectXBasicRendering\res\Shader\color.hlsl"
mov r0.xyz, v0.xyzx
mov r0.w, l(1.000000)
dp4 r1.x, r0.xyzw, cb0[0].xyzw  // r1.x <- posW.x
dp4 r1.y, r0.xyzw, cb0[1].xyzw  // r1.y <- posW.y
dp4 r1.z, r0.xyzw, cb0[2].xyzw  // r1.z <- posW.z
dp4 r1.w, r0.xyzw, cb0[3].xyzw  // r1.w <- posW.w

#line 36
dp4 r0.x, r1.xyzw, cb1[8].xyzw  // r0.x <- vOut.PosH.x
dp4 r0.y, r1.xyzw, cb1[9].xyzw  // r0.y <- vOut.PosH.y
dp4 r0.z, r1.xyzw, cb1[10].xyzw  // r0.z <- vOut.PosH.z
dp4 r0.w, r1.xyzw, cb1[11].xyzw  // r0.w <- vOut.PosH.w

#line 37
mov r1.xyzw, v1.xyzw  // r1.x <- vOut.Col.x; r1.y <- vOut.Col.y; r1.z <- vOut.Col.z; r1.w <- vOut.Col.w

#line 39
mov o0.xyzw, r0.xyzw
mov o1.xyzw, r1.xyzw
ret 
// Approximately 14 instruction slots used
